import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';
import tseslint from 'typescript-eslint';
import boundaries from 'eslint-plugin-boundaries';

// eslint-config-next is still eslintrc-format, so it is bridged in rather than
// spread directly.
const compat = new FlatCompat({
  baseDirectory: path.dirname(fileURLToPath(import.meta.url)),
});

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'dist/**',
      'playwright-report/**',
      // Generated by Next on every build; not ours to lint.
      'next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: { boundaries },
    settings: {
      'boundaries/elements': [
        { type: 'app', pattern: 'src/app/**' },
        { type: 'components', pattern: 'src/components/**' },
        { type: 'modules', pattern: 'src/modules/**' },
        { type: 'core', pattern: 'src/core/**' },
        { type: 'integrations', pattern: 'src/integrations/**' },
        { type: 'lib', pattern: 'src/lib/**' },
      ],
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      eqeqeq: ['error', 'always'],
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },

  // ---------------------------------------------------------------------------
  // Layering. This is a SECURITY control, not a style preference.
  //
  // Tenant isolation is enforced inside repositories, which inject `estateId`
  // into every query. Any code that reaches a Mongoose model directly bypasses
  // that guard and can read another estate's data. So: only repositories may
  // import schemas, and UI may never import a repository or a schema at all.
  // ---------------------------------------------------------------------------
  {
    files: ['src/app/**/*.{ts,tsx}', 'src/components/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/schema', '**/schema.ts', '@/modules/*/schema'],
              message:
                'UI and route files must not import Mongoose schemas. Call a service, which calls a repository. Repositories are the only layer permitted to touch models, because that is where estateId scoping is enforced.',
            },
            {
              group: ['**/repository', '**/repository.ts', '@/modules/*/repository'],
              message:
                'Do not call repositories directly from UI or route files. Go through the module service so business rules, entitlements and audit logging are applied.',
            },
            {
              group: ['mongoose'],
              message: 'Mongoose is server-data-layer only. Import the module service instead.',
            },
          ],
        },
      ],
    },
  },

  // Client components must never pull in server-only secrets or drivers.
  {
    files: ['src/components/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/core/config', '@/core/crypto', '@/core/db/*', '@/integrations/**'],
              message:
                'Components must not import server configuration, crypto or integration clients — that risks leaking secrets into the client bundle. Fetch through the API instead.',
            },
          ],
        },
      ],
    },
  },

  // Tests and scripts are trusted callers and may reach the data layer directly.
  {
    files: ['tests/**/*.ts', 'scripts/**/*.ts', 'src/**/*.test.ts'],
    rules: {
      'no-restricted-imports': 'off',
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
);
